aws-samples/aws-serverless-workshops

- lab2/admin/emails.html
- lab2/admin/index.html
- lab2/admin/login.html
- lab3/admin/index.html
- lab3/admin/post.html
Added html meta charset element to avoid browser warnings that may confuse the user.
> Add html meta charset element

- WebApplication/README.md
Fixed the links to modules 3 and 4 in the readme.
> Fixed links in README

- WebApplication/3_ServerlessBackend/README.md
- WebApplication/4_RESTfulAPIs/README.md
a couple of doc fix after going through the workshop
`WildRydesWebapp` to `WildRydesLambda`
/requestunicorn to /ride
> fix docs 'WildeRydesLambda' role and '/ride' resource

- WebApplication/1_StaticWebHosting/website/js/ride.js
- WebApplication/3_ServerlessBackend/requestUnicorn.js
Participants often miss the step of properly configuring authentication
for the POST method in API Gateway which results in a 502 error. Check
to ensure that authorization is configured and being passed by API
Gateway and improves error handling by displaying the error response to
the user in the JavaScript alert.
> Improve error handling

- WebApplication/1_StaticWebHosting/website/apply.html
- WebApplication/1_StaticWebHosting/website/faq.html
- WebApplication/1_StaticWebHosting/website/investors.html
- WebApplication/1_StaticWebHosting/website/unicorns.html
`scripts` folder doesn't exist, it was renamed/moved to `js`.
> Fix webapp JS assets folder

- DevOps/README.md
> Fixing Typo in README.md:23

- WebApplication/5_OAuth/README.md
Changes...
- Prereq: please clone the repo if skipped earlier modules and using cloudformation
- Step 4: NOT the "ListUnicornAuthorizer" function
- Step 5: call out "This bucket has public access" warning is expected
- Step 5.17: wording changes - not select 'Web' but under 'Web' section
> minor updates to README in 5_OAuth

- WebApplication/1_StaticWebHosting/README.md
- WebApplication/2_UserManagement/README.md
This contains a set of small fixes and enhancements based on Stockholm and Helsinki's workshop this week:
* Replaces `[BUCKET_NAME]` from instructions to `BUCKET_NAME`
* Updates IAM Policy to remove brackets from BUCKET_NAME
* Adds a small comment under `User Auth` to understand **Auth_token** received from the Web App using JWT.io as a decoder
> Quick fixes to WebApp based on last workshop's attendees feedback

- ImageProcessing/README.md
in clean up phase, remove the step to empty s3 buckets now the CFN template auto cleans up with custom resource
> [imagemodule] remove the step to empty s3 buckets

- DevOps/0_CodeStar/README.md
> Cleaned up duplicate text

- WebApplication/1_StaticWebHosting/README.md
> Updated README.md

- DevOps/1_ServerlessApplicationModel/README.md
- WebApplication/2_UserManagement/README.md
Readme updates that include updated instructions, links and tool naming for SAM CLI. 
Includes modification for introduced in #152
> Updates to DevOps Module 1: Serverless Application Model README

- README.md
add link to the new serverless security workshop from the main README
> add link to serverless security workshop

- WebApplication/3_ServerlessBackend/README.md
#161 
Manual merge due to recent changes breaking this PR #161 
> manual merge of PR-161

- WebApplication/4_RESTfulAPIs/README.md
- WebApplication/6_GraphQLAPI/README.md
- WebApplication/9_CleanUp/README.md
Updates the Cleanup step to include Module 6 as well as the Cloud9 created in the Setup. Changes some look and feel to unhide the main 4 modules so that nothing is missed.
- Chris Munns
munns@amazon.com
Principal Developer Advocate - Serverless
> Update WebApps Cleanup for new Module 6 and look and feel

- WebApplication/1_StaticWebHosting/README.md
Updated Code-Commit example in web hosting to utilize the awc-cli credentials helper.
> Credentials helper

- Auth/website/src/auth/SignIn.js
- Auth/website/src/auth/SignUp.js
Changed form-level password validation to minimal character length to allow server-side validations to surface from Cognito User Pools
> Updated form-based password min length to 2+ characters

- Auth/0_GettingStarted/Cloud9WithNewVPC.yaml
- Auth/1_UserAuthentication/README.md
- Auth/2_ServerlessAPI/ServerlessBackend.yaml
Updating Auth Workshop- Module 1 instructiosn to reference new UI changes for SES  in creating new Cognito User pool.  Removing reference to re:invent in cloudformation templates
> Update Auth Module 1 instructions

- Auth/0_GettingStarted/Cloud9WithNewVPC.yaml
Add end quote on line 9 of YAML
> fix typo, add end quote to description

- WebApplication/1_StaticWebHosting/README.md
No issue pertains to this.
I am doing a workshop with @ramjetty and the page changed during the workshop, so I figured I may as well submit an update since the repos open source :)
Feel free to close if bigger changes already take care of this!
Best,
Bobby
> Update copy from deploy page for amplify console step per new UI on site

- DevOps/2_ContinuousDeliveryPipeline/README.md
Reference to wrong section in buildspec.yml (build instead of pre_build).
Change reference to pre_build.
> Fix reference

- ImageProcessing/README.md
Changed the instructions to click "Create Stack" instead of "Create Change Set", which was causing issues with students in the lab.
> Update CloudFormation execute step

- WebApplication/1_StaticWebHosting/README.md
*Description of changes:* Fixing small typo. rendorings becomes renderings
> fix typo: rendorings -> renderings

- WebApplication/1_StaticWebHosting/README.md
*Issue #, if available:* #253 
*Description of changes:*  Clarified Git repository options.
> Fix for issue #253 - clarifying Git repo options

- README.md
> Updated parent read me file to include other missing workshops

- MachineLearning/2_ModelBuilding/README.md
> Updating reference to ML notebook.

- WebApplication/README.md
N/A
Updated WebApplication README to point to new source repo on GitHub.
> Updated WebApplication README to point to new source repo on GitHub.

- ImageProcessing/src/cloudformation/module-setup.yaml
- ImageProcessing/workshop/static/cloudformation/sam.yaml
Updated runtimes in templates to use nodejs14 and python3.6
> Updated runtimes to nodejs14.x and python3.6

- ImageProcessing/workshop/static/cloudformation/sam_220615.yaml
Simple update of python runtime from 3.6 (now depricated) to 3.9. 
> Updated python runtime version from 3.6 to 3.9
